// <auto-generated />
using System;
using CodeFirstLibrary.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace NetCore.CodeFirstLibrary.DataAccess.Migrations
{
    [DbContext(typeof(AirCraftContext))]
    [Migration("20190829101213_CodeFirstLibrary.DataAccess.AirCraftContext")]
    partial class CodeFirstLibraryDataAccessAirCraftContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeFirstLibraryDataAccess.Models.AirCraft", b =>
                {
                    b.Property<int>("AircraftId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<byte[]>("Photo");

                    b.Property<decimal>("Winspan");

                    b.HasKey("AircraftId");

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("CodeFirstLibraryDataAccess.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AircraftId");

                    b.Property<string>("Customer");

                    b.Property<bool>("IsCompleted");

                    b.HasKey("OrderId");

                    b.HasIndex("AircraftId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CodeFirstLibraryDataAccess.Models.Order", b =>
                {
                    b.HasOne("CodeFirstLibraryDataAccess.Models.AirCraft", "Aircraft")
                        .WithMany("Orders")
                        .HasForeignKey("AircraftId");
                });
#pragma warning restore 612, 618
        }
    }
}
